### PR TITLE
Removed span that has the class of the form "CharOverride-xxx"

### PR DESCRIPTION
**Pull request by brunobord**
I've checked on the BitD website, they have no semantic or stylistic difference.

### CODE REVIEW

**Comment by brunobord** [comment]
@amazingrando just to make sure: are you interested in these kinds of pull-requests or not?

**Comment by amazingrando** [comment]
I am. Somehow I never noticed this. I will review it today.

**Review by amazingrando — APPROVED** [review]
Looks great! Thanks for the help.

**Comment by brunobord** [comment]
you're very welcome! thx for the great work on the SRD!

**Pull request merged**
